notifications:
  email: false
language: julia
os:
  - linux
env:
  - PYTHON="" CONDA_JL_VERSION=3
matrix:
  include:
    - julia: 0.6
      script:
        - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
        - julia -e 'Pkg.clone(pwd())'
        - julia -e 'Pkg.build("HartreeFockBogoliubov")'
        - julia -e 'Pkg.test("HartreeFockBogoliubov", coverage=true)'
      after_success:
        - julia -e 'cd(Pkg.dir("HartreeFockBogoliubov")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
        - julia -e 'Pkg.add("Documenter")'
        - julia -e 'cd(Pkg.dir("HartreeFockBogoliubov")); include(joinpath("docs", "make.jl"))'
    - julia: 0.7
      script:
        - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
        - julia -e 'Pkg.build()'
        - julia -e 'Pkg.test("HartreeFockBogoliubov", coverage=true)'
      after_success:
        - julia -e 'cd(Pkg.dir("HartreeFockBogoliubov")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia: nightly
      script:
        - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
        - julia -e 'Pkg.build()'
        - julia -e 'Pkg.test("HartreeFockBogoliubov", coverage=true)'
      after_success:
        - julia -e 'cd(Pkg.dir("HartreeFockBogoliubov")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
