version: 2
jobs:
  build:
    working_directory: ~/hfbtest
    docker:
      - image: julia:0.6.0
    steps:
      - checkout
      - run:
          name: greeting
          command: 'julia --version'
      - store_artifacts:
        path: test-greeting.xml
        prefix: tests
