version: 2
jobs:
  build:
    working_directory: ~/hfbtest
    docker:
      - image: julia:0.6.0
    steps:
      - checkout
      - run:
          name: greeting
          command: 'julia --version'
      - run:
          name: whereami
          command: |
            pwd
            ls
      - run:
          name: preinstall
          command: |
            julia -e 'Pkg.add("ProgressMeter")'
            julia -e 'Pkg.add("DataStructures")'
            julia -e 'Pkg.clone(pwd())'
      - run:
          name: test
          command: |
            julia -e 'Pkg.test("HartreeFockBogoliubov")'
      - store_artifacts:
          path: test-greeting.xml
          prefix: tests
