site_name: HartreeFockBogoliubov.jl

repo_url: https://github.com/kyungminlee/HartreeFockBogoliubov.jl
site_description: Hartree-Fock-Bogoliubov Solver
site_author: kyungminlee

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Basics:
    - Hartree-Fock-Bogoliubov Theory: basics/hartreefockbogoliubov.md
    - Momentum Space Formulation: basics/momentumspace.md
  - About: about.md
