site_name: HartreeFockBogoliubov.jl

site_description: Hartree-Fock-Bogoliubov Solver
site_author: kyungminlee
site_url: https://kyungminlee.org/HartreeFockBogoliubov.jl/
repo_url: https://github.com/kyungminlee/HartreeFockBogoliubov.jl

copyright: Copyright (c) 2016 Kyungmin Lee

theme: mkdocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite
  - def_list
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Basic Theory:
    - Hartree-Fock-Bogoliubov Theory: basics/hartreefockbogoliubov.md
    - Hartree-Fock-Bogoliubov Equations: basics/hfbequation.md
    - Hartree-Fock-Bogoliubov Decomposition: basics/hfbdecomposition.md
    - Momentum Space Formulation: basics/momentumspace.md
    - Topological Invariants: basics/topology.md
  - User Guide:
      - Lattice: guide/lattice.md
      - Hamiltonian: guide/hamiltonian.md
      - HFB: guide/hfb.md
      - Linearized Gap Equation: guide/linearizedgap.md
      - Topology: guide/topology.md
      - Example: guide/example.md
  - Internals:
    - Internals: internals.md
    - More: internals/hartreefockbogoliubov.md
